ifndef BOOSTDIR
BOOSTDIR = ../../boost_1_33_0
endif

CXXFLAGS = -g -O2 -Wall -mthreads -I../include -I$(BOOSTDIR)
LDFLAGS = -g -O2 -mthreads
LIBS = -lws2_32
DEFINES = -D_WIN32_WINNT=0x0500

PERFORMANCE_TEST_EXES = \
	tests/performance/client.exe \
	tests/performance/server.exe

UNIT_TEST_EXES = \
	tests/unit/basic_datagram_socket_test.exe \
	tests/unit/basic_deadline_timer_test.exe \
	tests/unit/basic_demuxer_test.exe \
	tests/unit/basic_locking_dispatcher_test.exe \
	tests/unit/basic_socket_acceptor_test.exe \
	tests/unit/basic_stream_socket_test.exe \
	tests/unit/buffer_test.exe \
	tests/unit/buffered_read_stream.exe \
	tests/unit/buffered_stream.exe \
	tests/unit/buffered_write_stream.exe \
	tests/unit/buffers_test.exe \
	tests/unit/datagram_socket_test.exe \
	tests/unit/deadline_timer_test.exe \
	tests/unit/demuxer_test.exe \
	tests/unit/error_handler_test.exe \
	tests/unit/fixed_buffer_test.exe \
	tests/unit/ipv4_host_resolver_test.exe \
	tests/unit/is_read_buffered_test.exe \
	tests/unit/is_write_buffered_test.exe \
	tests/unit/locking_dispatcher_test.exe \
	tests/unit/read_test.exe \
	tests/unit/write_test.exe \
	tests/unit/socket_acceptor_test.exe

EXAMPLE_EXES = \
	examples/chat/chat_client.exe \
	examples/chat/chat_server.exe \
	examples/echo/async_tcp_echo_server.exe \
	examples/echo/async_udp_echo_server.exe \
	examples/echo/blocking_tcp_echo_client.exe \
	examples/echo/blocking_tcp_echo_server.exe \
	examples/echo/blocking_udp_echo_client.exe \
	examples/echo/blocking_udp_echo_server.exe \
	examples/multicast/receiver.exe \
	examples/multicast/sender.exe \
	examples/timeouts/accept_timeout.exe \
	examples/timeouts/connect_timeout.exe \
	examples/timeouts/datagram_receive_timeout.exe \
	examples/timeouts/stream_receive_timeout.exe \
	examples/tutorial/timer1/timer.exe \
	examples/tutorial/timer2/timer.exe \
	examples/tutorial/timer3/timer.exe \
	examples/tutorial/timer4/timer.exe \
	examples/tutorial/timer5/timer.exe \
	examples/tutorial/daytime1/client.exe \
	examples/tutorial/daytime2/server.exe \
	examples/tutorial/daytime3/server.exe \
	examples/tutorial/daytime4/client.exe \
	examples/tutorial/daytime5/server.exe \
	examples/tutorial/daytime6/server.exe \
	examples/tutorial/daytime7/server.exe

all: \
	$(PERFORMANCE_TEST_EXES) \
	$(UNIT_TEST_EXES) \
	$(EXAMPLE_EXES)

check: $(UNIT_TEST_EXES) $(addprefix run.,$(UNIT_TEST_EXES))

$(addprefix run.,$(UNIT_TEST_EXES))::
	@echo === Running $(@:run.%=%) ===
	@$(@:run.%=%)
	@echo.

clean:
	-rm -f $(PERFORMANCE_TEST_EXES)
	-rm -f $(PERFORMANCE_TEST_EXES:.exe=.o)
	-rm -f $(UNIT_TEST_EXES)
	-rm -f $(UNIT_TEST_EXES:.exe=.o)
	-rm -f $(EXAMPLE_EXES)
	-rm -f $(EXAMPLE_EXES:.exe=.o)

$(PERFORMANCE_TEST_EXES) $(UNIT_TEST_EXES) $(EXAMPLE_EXES): %.exe: %.o
	g++ -o$@ $(LDFLAGS) $< $(LIBS)

.cpp.o:
	g++ -o$@ -c $(CXXFLAGS) $(DEFINES) $<
